# This file contains the list of animals that will be found in the app's dropdown menus

animals = [
    "Alligator",
    "Anaconda",
    "Black Bear",
    "Bull Shark",
    "Cheetah",
    "Crocodile",
    "Eagle",
    "Electric Eel",
    "Elephant",
    "Falcon",
    "Giraffe",
    "Gorilla",
    "Great White Shark",
    "Grizzly Bear",
    "Hawk",
    "Hippopotamus",
    "Honey Badger",
    "Hyena",
    "Jaguar",
    "King Cobra",
    "Komodo Dragon",
    "Lion",
    "Moose",
    "Orangutan",
    "Orca",
    "Ostrich",
    "Polar Bear",
    "Rhinoceros",
    "Sperm Whale",
    "Stingray",
    "Tiger",
    "Tiger Shark",
    "Vulture",
    "Walrus",
    "Wild Boar",
    "Wolf",
    "Wolverine",
]